name: Tests

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Jest
      env:
        MONGO_CONNECTION_STRING: ${{secrets.MONGO_CONNECTION_STRING}}
      uses: stefanoeb/jest-action@1.0.3