name: Tests

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Jest
      env:
        MY_VAR: env var hello world!
      run: yarn test --cs=$MY_VAR
      uses: stefanoeb/jest-action@1.0.2